### ISSUE TITLE
Incorrectly converted spread operator on string

### ISSUE THREAD

**Issue by kshetline** [rollup/rollup-plugin-buble#14]
I had a function in my code that was meant to transform a base64-encoded string into a Uint8Array:

`base64 => new Uint8Array([...atob(base64)].map(char => char.charCodeAt(0))); `

Buble unfortunately converts the above code into this:

`function (base64) { return new Uint8Array([].concat( atob(base64) ).map(function (char) { return char.charCodeAt(0); })); };`

Instead of splitting the string value `atob(base64)` up into an array of individual characters, all that was produced was an array of length one, with the entire unbroken string inside the array as the single element. The result was that no matter how long the base64 input was, only a single-byte array would be produced.

I was able to work around the problem by changing the original code to this:

`base64 => new Uint8Array(atob(base64).split('').map(char => char.charCodeAt(0)));`

Even though I have a workaround for now, I thought you might want to know about this bug.

**Comment by eventualbuddha** [comment]
This issue is probably a buble issue, not a rollup plugin issue. @Rich-Harris or someone with access, maybe move this to https://github.com/bublejs/buble?

**Comment by kshetline** [comment]
I took care of reporting this issue at https://github.com/bublejs/buble myself. Thanks!

**Comment by wesleygrimes** [comment]
The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @wesleygrimes and request a re-open, and we'll be happy to oblige.
