### ISSUE TITLE
error with => synthax on class attribute

### ISSUE THREAD

**Issue by Makio64** [rollup/rollup-plugin-buble#15]
Hello, the synthax bellow produce an error at the parsing, is there any way to fix this ?

```
class A {
   
    update = ()=>{ // produce an error

   }

}
```

It corresponds to the stage3 babel/plugin-proposal-class-properties

Thanks!

**Comment by wesleygrimes** [comment]
The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @wesleygrimes and request a re-open, and we'll be happy to oblige.
