### ISSUE TITLE
npm still points to old repo

### ISSUE THREAD

**Issue by rbrtmrtn** [rollup/rollup-plugin-buble#6]
Pretty minor, but just wanted to point out -- the two repository links on the npm page for `rollup-plugin-buble` on npm still point to the old GitLab repo:

https://www.npmjs.com/package/rollup-plugin-buble

![image](https://user-images.githubusercontent.com/1463553/37716896-eff4db9c-2cf5-11e8-846a-7d3abad21170.png)

**Comment by rbrtmrtn** [comment]
Just realized this is a dupe of #5. Seems like npm is still hanging onto that version, for some reason.

**Comment by curran** [comment]
Still pointing to GitLab.

**Comment by irrg** [comment]
Still pointing to GitLab.

**Comment by adrianheine** [comment]
Thanks for the nagging, it's done now.
